### ISSUE TITLE
get user name from $USER variable

### ISSUE THREAD

**Issue by kevcenteno** [pseudomuto/dotfiles#1]
In your readme, you have this:

```
chsh -s /usr/local/bin/zsh <username>
```

which requires you to replace `<username>` with some string (presumably the current user's username)

Instead, you can just do this

```
chsh -s /usr/local/bin/zsh $USER
```

`$USER` is an internal variable that returns the _current_ user's username.

**Comment by pseudomuto** [comment]
Good point, but I've remove that since. I figured people can look up the command...README is stripped down to almost nothing now
